
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="index#page-top">
                    <!-- <i class="fa fa-play-circle"></i>  -->
                    <img src="img/kuyo_mon_14x14.jpg"/>
                    <span class="light red">Shinkendo UK</span>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="index#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="index#about">About</a>
                    </li>
                    <li class="dropdown">
			          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Learn more <span class="caret"></span></a>
			          <ul class="dropdown-menu" role="menu">
			            <li><a href="learn#shinkendo">Shinkendo</a></li>
			            <li><a href="learn#toyamaryu">Toyama-Ryu</a></li>
			            <li><a href="learn#aikubujutsu">Aikibujutsu</a></li>
			            <li class="divider"></li>
			            <!-- li><a href="#terminology">Terminology</a></li -->
			          </ul>
			        </li>
			        <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Instructors <span class="caret"></span></a>
	                      <ul class="dropdown-menu" role="menu">
	                        <li><a href="instructors#obata">Obata Sensei</a></li>
                            <li><a href="instructors#shepherd">Shepherd Sensei</a></li>
                            <li><a href="instructors#dunkley">Dunkley Sensei</a></li>
                            <li><a href="instructors#hunter">Hunter Sensei</a></li>
                            <li><a href="instructors#bauling">Bauling Sensei</a></li>
	                      </ul>
                    </li>
		    <li>
		    	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Experience <span class="caret"></span></a>
			   <ul class="dropdown-menu" role="menu">
                       <li><a href="experience#dojo">Dojo</a></li>
	                     <li><a href="experience#classes">Classes &amp; Seminars</a></li>
	                     <li><a href="experience#video">Video</a></li>
                       <li><a href="experience#dvd">DVD</a></li>
                       <li><a href="experience#records">records</a></li>
                       <li><a href="experience#shirt">T-Shirt</a></li>
	                  </ul>
                    </li>

                    <li>
                        <a class="page-scroll" href="contact">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
